#pragma once
// Everything the editor WRITES into a PROJECT folder: the `.ocproject` scaffold behind
// New Project, and the C# script/class + `.csproj` behind Tools > New C# Script / New C# Class.
//
// Split out from the UI on purpose — every entry point needs the same validation and the same
// refuse-to-overwrite rule, and none should be reasoning about paths inside an ImGui frame.
// Engine-side authoring (Tools > New C++ ...) is EngineScaffold.hpp: adding C# needs no rebuild,
// adding C++ does, and keeping them in one file would blur exactly the line that matters.
#include "aver/formats/OcProject.hpp"

#include <string>

namespace aver::editor {

// A project folder name must survive being a directory name AND a manifest NAME. Rejects empty,
// path separators, the Windows-reserved punctuation, and leading/trailing dots or spaces.
bool validateProjectName(const std::string& name, std::string* err);

// A type name: leading letter or '_', then letters/digits/'_'. Also rejects the handful of
// keywords a generated `class <Name>` would not compile with. Shared by every Tools > New ...
// item — the C# and C++ rules coincide for the subset a generated file may use, and one rule
// means one error message rather than four that drift apart.
bool validateTypeName(const std::string& name, std::string* err);

// Write `text` to `path`, refusing to touch a file that is already there. Every Tools > New ...
// item goes through this: overwriting someone's work on a name clash is the one failure mode
// none of them may have, so it is enforced in a single place instead of four.
bool writeNewFile(const std::string& path, const std::string& text, std::string* err);

// Create `<location>\<name>\` with the manifest and Content tree docs/PROJECTS.md specifies.
// Refuses to touch an existing folder rather than merging into it — a half-scaffolded project on
// top of someone's data is worse than a failed button.
bool scaffoldProject(const std::string& location, const std::string& name,
                     fmt::ProjectDesc& out, std::string* err);

// What a generated `.cs` is FOR. Both land in the same folder and compile the same way; the
// difference is only whether the file pretends to have a lifecycle. It matters because the
// engine cannot call a lifecycle hook yet, so offering only the hooked template implies a
// runtime that is not there.
enum class CsKind {
    Behaviour,  // OnStart/OnUpdate hooks, in the shape an eventual CLR host would call
    PlainClass, // no hooks — data, helpers, anything that is just C#
};

// Write `<project>\Content\Scripts\<name>.cs`, plus the folder's `.csproj` if it is not there yet.
// Never overwrites an existing `.cs`. `outPath` receives the file written; `outCsproj` is set when
// the project file was generated by this call.
bool createScript(const fmt::ProjectDesc& proj, const std::string& name, CsKind kind,
                  std::string* outPath, bool* outCsproj, std::string* err);

// Absolute path of the `.csproj` Tools > New C# Script generates, whether or not it exists yet.
// Compile Scripts and Open in Visual Studio both need to name it before it is there.
std::string scriptsCsprojPath(const fmt::ProjectDesc& proj);

} // namespace aver::editor
