#pragma once
// Everything the editor WRITES into a PROJECT folder: the `.ocproject` scaffold behind
// New Project, and the C# script/class + `.csproj` behind Tools > New C# Script / New C# Class.
//
// Split out from the UI on purpose — every entry point needs the same validation and the same
// refuse-to-overwrite rule, and none should be reasoning about paths inside an ImGui frame.
// Engine-side authoring (Tools > New C++ ...) is EngineScaffold.hpp: adding C# needs no rebuild,
// adding C++ does, and keeping them in one file would blur exactly the line that matters.
#include "aver/formats/OcProject.hpp"

#include <string>
#include <vector>

namespace aver::editor {

// A project folder name must survive being a directory name AND a manifest NAME. Rejects empty,
// path separators, the Windows-reserved punctuation, and leading/trailing dots or spaces.
bool validateProjectName(const std::string& name, std::string* err);

// A type name: leading letter or '_', then letters/digits/'_'. Also rejects the handful of
// keywords a generated `class <Name>` would not compile with. Shared by every Tools > New ...
// item — the C# and C++ rules coincide for the subset a generated file may use, and one rule
// means one error message rather than four that drift apart.
bool validateTypeName(const std::string& name, std::string* err);

// Write `text` to `path`, refusing to touch a file that is already there. Every Tools > New ...
// item goes through this: overwriting someone's work on a name clash is the one failure mode
// none of them may have, so it is enforced in a single place instead of four.
bool writeNewFile(const std::string& path, const std::string& text, std::string* err);

// Create `<location>\<name>\` with the manifest and Content tree docs/PROJECTS.md specifies.
// Refuses to touch an existing folder rather than merging into it — a half-scaffolded project on
// top of someone's data is worse than a failed button.
bool scaffoldProject(const std::string& location, const std::string& name,
                     fmt::ProjectDesc& out, std::string* err);

// What a generated `.cs` is FOR — the base type it derives, which decides the hooks the engine
// calls and (for the actor kinds) the gameplay flag its registry row gets. All of them compile into
// the same assembly; the base class is how the COMPILER, not an attribute, decides which hooks a
// script has, so a misspelt override is a build error rather than a method that silently never runs.
//
// Behaviour is the one that RUNS TODAY. The actor kinds compile against Aver.Framework but do not
// tick yet — the framework's tick/discovery and its native ABI are steps 9-11 — so a scaffolded
// Pawn builds green and then does nothing until that lands. The templates say so.
enum class CsKind {
    Behaviour,         // : AverBehaviour  — OnStart/OnUpdate/OnShutdown, runs today
    Actor,             // : AverActor      — a thing in the world with a transform + lifecycle
    Pawn,              // : AverPawn       — an Actor a controller can possess
    PlayerController,  // : AverPlayerController — input + camera; possesses a pawn
    GameMode,          // : AverGameMode   — per-world rules; names the default pawn/controller
    GameInstance,      // : AverGameInstance — process-wide state that spans levels
    PlainClass,        // no base, no hooks — data, helpers, anything that is just C#
};

// True for anything the engine drives by a lifecycle — Behaviour or any actor kind. A plain class
// is the only kind that is not a "script".
bool csKindIsScript(CsKind kind);

// True for the framework actor kinds. These need the project to reference Aver.Framework, which is
// why a project that scaffolds one gets that reference added to its `.csproj`.
bool csKindIsActor(CsKind kind);

// The human word for a kind, for menu labels and log lines ("Pawn", "GameMode", "script", "class").
const char* csKindNoun(CsKind kind);

// Write `<project>\Content\Scripts\<name>.cs`, plus the folder's `.csproj` if it is not there yet.
// Never overwrites an existing `.cs`. `outPath` receives the file written; `outCsproj` is set when
// the project file was generated by this call.
bool createScript(const fmt::ProjectDesc& proj, const std::string& name, CsKind kind,
                  std::string* outPath, bool* outCsproj, std::string* err);

// Absolute path of the `.csproj` Tools > New C# Script generates, whether or not it exists yet.
// Compile Scripts and Open in Visual Studio both need to name it before it is there.
std::string scriptsCsprojPath(const fmt::ProjectDesc& proj);

// `<project>\Binaries\Scripts` — the ONE directory a project's script assemblies live in.
//
// It is a function rather than a `.csproj` property because both ends have to agree and only one
// of them is ours to edit: Tools > Compile Scripts passes it to `dotnet build -o`, and the
// scripting host is pointed at the same string. Putting it in the generated `.csproj` instead
// would leave every project scaffolded before this change building somewhere the host does not
// look, with nothing anywhere saying why the scripts did not load.
//
// OUTSIDE `Content\`, deliberately: `Content` is the asset mount root a shipped game reads, and
// build output is neither content nor something anyone should ship.
std::string scriptsBinaryDir(const fmt::ProjectDesc& proj);

// ---------------------------------------------------------------- upgrading an older project
//
// What a project needs has grown: four engine references where there was one, a Materials folder
// with a Compile glob pointing at it, a `.csproj` that exists before the first script. A project
// scaffolded before any of that is not broken in a way it can report -- it simply fails to build a
// HUD, or bakes no materials, with an error naming an assembly nobody chose.
//
// So the editor looks when it opens one, and ASKS. It never modifies a project silently: the files
// belong to whoever wrote them, and a tool that edits your build on startup is a tool you cannot
// trust with the rest.

// One thing that is missing, and what would be done about it.
struct ProjectFix {
    enum class Kind {
        CreateFolder,      // a Content subfolder the layout expects
        CreateCsproj,      // no Scripts.csproj at all
        AddReference,      // an engine assembly the .csproj does not name
        AddMaterialsGlob,  // the <Compile Include="..\Materials\**\*.cs" /> item
        RepointReference,  // a ProjectReference whose target does not exist (a moved or deleted tree)
    };
    Kind kind = Kind::CreateFolder;
    std::string summary;   // one line, for the prompt
    std::string detail;    // the path, or the exact text that would be inserted
};

struct ProjectUpgrade {
    std::vector<ProjectFix> fixes;
    bool empty() const { return fixes.empty(); }
};

// What `proj` is missing. Reads only; writes nothing. An empty result means the project is current.
ProjectUpgrade inspectProject(const fmt::ProjectDesc& proj);

// Apply everything `inspectProject` found.
//
// The `.csproj` is MERGED, never regenerated: a project may carry a PropertyGroup, a
// PackageReference or a target somebody added by hand, and replacing the file to add a reference
// would throw all of it away. Missing items are appended as a new ItemGroup before `</Project>`,
// which MSBuild merges with whatever is already there.
//
// Returns false with `err` set on the first failure, having applied whatever came before it.
bool applyProjectUpgrade(const fmt::ProjectDesc& proj, const ProjectUpgrade& up, std::string* err);

} // namespace aver::editor
