#include "ProjectScaffold.hpp"

#include "aver/platform/FileSystem.hpp"
#include "aver/core/Version.hpp"
#include "aver/core/Log.hpp"

#include <algorithm>
#include <filesystem>

namespace aver::editor {
namespace {

constexpr const char* kCsprojName = "Scripts.csproj";

// Where Aver.Scripting lives, expressed relative to a project's Scripts folder.
//
// A project is a SIBLING of the engine, never inside it, so the reference has to reach back out
// of the projects root. The engine root is found by walking up from the executable rather than
// assumed to be two levels above bin/, because that only holds for the default build layout.
std::string scriptingProjectReference(const std::string& scriptsDir) {
    std::error_code ec;
    std::filesystem::path probe = std::filesystem::path(executableDir());
    const std::filesystem::path tail = "scripting/csharp/Aver.Scripting/Aver.Scripting.csproj";
    for (int up = 0; up < 8 && !probe.empty(); ++up) {
        const std::filesystem::path candidate = probe / tail;
        if (std::filesystem::exists(candidate, ec)) {
            const std::filesystem::path rel = std::filesystem::relative(candidate, scriptsDir, ec);
            std::string s = ec || rel.empty() ? candidate.string() : rel.string();
            std::replace(s.begin(), s.end(), '/', '\\'); // MSBuild convention
            return s;
        }
        if (!probe.has_parent_path() || probe.parent_path() == probe) break;
        probe = probe.parent_path();
    }
    return {};
}

std::string manifestText(const std::string& name) {
    std::string s;
    s += "OCPROJECT 1\n";
    s += "# Created by the Aver Engine editor. This project lives OUTSIDE the engine tree and\n";
    s += "# references it; see the engine's docs/PROJECTS.md.\n";
    s += "NAME " + name + "\n";
    s += "ENGINE " + std::string(kEngineName) + " " + std::string(kEngineVersion) + "\n";
    s += "CONTENT Content\n";
    // The editor cannot author or save a map yet (docs/STATUS.md 4d), so this names where the
    // start map WILL go rather than a file that exists. Loading is tolerant of the gap.
    s += "STARTMAP Maps/Default.ocmap\n";
    // Left commented rather than written empty: the editor has no author field to fill it from,
    // and `AUTHOR` with nothing after it reads as a value someone deleted.
    s += "# AUTHOR <your name>\n";
    return s;
}

std::string csprojText(const std::string& reference) {
    std::string s;
    s += "<Project Sdk=\"Microsoft.NET.Sdk\">\n\n";
    s += "  <!-- Generated by the Aver Engine editor (Tools > New C# Script).\n";
    s += "       A class library, not an exe: the engine has no in-process CLR host yet, so nothing\n";
    s += "       here is ever executed. It exists so the scripts in this folder compile and get\n";
    s += "       IntelliSense against the real API. See the engine's docs/STATUS.md 4d. -->\n";
    s += "  <PropertyGroup>\n";
    s += "    <TargetFramework>net10.0</TargetFramework>\n";
    s += "    <Nullable>enable</Nullable>\n";
    s += "    <ImplicitUsings>enable</ImplicitUsings>\n";
    s += "  </PropertyGroup>\n\n";
    if (reference.empty()) {
        s += "  <!-- The engine's Aver.Scripting.csproj could not be located from the editor's\n";
        s += "       install path. Point this at <engine>\\scripting\\csharp\\Aver.Scripting. -->\n";
        s += "  <!-- <ItemGroup>\n";
        s += "    <ProjectReference Include=\"..\\..\\..\\..\\Aver Engine\\scripting\\csharp\\Aver.Scripting\\Aver.Scripting.csproj\" />\n";
        s += "  </ItemGroup> -->\n\n";
    } else {
        s += "  <ItemGroup>\n";
        s += "    <ProjectReference Include=\"" + reference + "\" />\n";
        s += "  </ItemGroup>\n\n";
    }
    s += "</Project>\n";
    return s;
}

std::string scriptText(const std::string& projectName, const std::string& scriptName) {
    std::string s;
    s += "// " + scriptName + ".cs - a script in the '" + projectName + "' project.\n";
    s += "//\n";
    s += "// THIS SCRIPT DOES NOT RUN YET. The engine cannot host the CLR in-process, so nothing\n";
    s += "// loads or calls this file (see the engine's docs/STATUS.md 4d). It compiles, it gets\n";
    s += "// IntelliSense, and the API below is real - a standalone C# process can call it today\n";
    s += "// (scripting/csharp/Aver.Scripting.Sample) - but the editor will not execute it.\n";
    s += "//\n";
    s += "// What Aver.Scripting actually exposes right now is the Voxi render module's settings\n";
    s += "// and this machine's GPU capabilities.\n";
    s += "\n";
    s += "using Aver.Scripting;\n";
    s += "\n";
    s += "namespace " + projectName + ";\n";
    s += "\n";
    s += "public sealed class " + scriptName + "\n";
    s += "{\n";
    s += "    public void OnStart()\n";
    s += "    {\n";
    s += "        // Ask before setting: a feature the GPU or the renderer cannot do reports its\n";
    s += "        // real status instead of pretending, and assigning it leaves the value at Off.\n";
    s += "        if (Voxi.IsAvailable(VoxiFeature.GlobalIllumination))\n";
    s += "            Voxi.GlobalIllumination = VoxiQuality.High;\n";
    s += "\n";
    s += "        Console.WriteLine($\"Ray tracing tier: {Voxi.RayTracingTier}\");\n";
    s += "        Console.WriteLine($\"Max MSAA: {Voxi.MaxMsaa}x\");\n";
    s += "    }\n";
    s += "}\n";
    return s;
}

} // namespace

bool validateProjectName(const std::string& name, std::string* err) {
    auto fail = [&](const char* m) { if (err) *err = m; return false; };
    if (name.empty()) return fail("Enter a project name.");
    if (name.size() > 64) return fail("Name is too long (64 characters max).");
    for (const char c : name) {
        if (c == '/' || c == '\\') return fail("A name cannot contain a path separator.");
        if (c == ':' || c == '*' || c == '?' || c == '"' || c == '<' || c == '>' || c == '|')
            return fail("A name cannot contain : * ? \" < > or |");
        if (static_cast<unsigned char>(c) < 0x20) return fail("A name cannot contain control characters.");
    }
    if (name.front() == ' ' || name.back() == ' ' || name.back() == '.')
        return fail("A name cannot start or end with a space, or end with a dot.");
    return true;
}

bool validateScriptName(const std::string& name, std::string* err) {
    auto fail = [&](const char* m) { if (err) *err = m; return false; };
    if (name.empty()) return fail("Enter a script name.");
    if (name.size() > 64) return fail("Name is too long (64 characters max).");
    const char f = name.front();
    if (!((f >= 'A' && f <= 'Z') || (f >= 'a' && f <= 'z') || f == '_'))
        return fail("A script name must start with a letter or underscore.");
    for (const char c : name) {
        const bool ok = (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_';
        if (!ok) return fail("Use letters, digits and underscores only - this becomes a C# class name.");
    }
    // `class class` does not compile, and the file would look fine until someone built it.
    static const char* kReserved[] = {"class", "struct", "int", "float", "double", "bool", "string",
                                      "void", "public", "private", "static", "namespace", "using",
                                      "new", "this", "base", "null", "true", "false", "object"};
    for (const char* r : kReserved)
        if (name == r) return fail("That is a C# keyword and cannot be a class name.");
    return true;
}

bool scaffoldProject(const std::string& location, const std::string& name,
                     fmt::ProjectDesc& out, std::string* err) {
    if (!validateProjectName(name, err)) return false;
    if (location.empty()) { if (err) *err = "Choose a location."; return false; }

    const std::string root = location + "\\" + name;
    if (fileExists(root)) {
        if (err) *err = "A folder already exists at " + root;
        return false;
    }

    const std::string content = root + "\\Content";
    // Maps/Meshes/Scripts is the layout docs/PROJECTS.md specifies; creating them up front is what
    // makes the Content Browser and Tools > New C# Script have somewhere to point at once.
    for (const std::string& d : {content + "\\Maps", content + "\\Meshes", content + "\\Scripts"}) {
        if (!createDirectories(d)) {
            if (err) *err = "Could not create " + d;
            return false;
        }
    }

    const std::string manifest = root + "\\" + name + ".ocproject";
    if (!writeFileText(manifest, manifestText(name))) {
        if (err) *err = "Could not write " + manifest;
        return false;
    }

    if (!fmt::loadOcproject(manifest, out, err)) return false;
    AVER_INFO("[Editor] created project '{}' at {}", name, root);
    return true;
}

bool createScript(const fmt::ProjectDesc& proj, const std::string& name,
                  std::string* outPath, bool* outCsproj, std::string* err) {
    if (outCsproj) *outCsproj = false;
    if (!validateScriptName(name, err)) return false;
    if (!proj.valid()) { if (err) *err = "No project is loaded."; return false; }

    const std::string dir = proj.scriptsDir();
    if (!createDirectories(dir)) {
        if (err) *err = "Could not create " + dir;
        return false;
    }

    const std::string path = dir + "\\" + name + ".cs";
    if (fileExists(path)) {
        if (err) *err = name + ".cs already exists in Content\\Scripts.";
        return false;
    }
    if (!writeFileText(path, scriptText(proj.name, name))) {
        if (err) *err = "Could not write " + path;
        return false;
    }
    if (outPath) *outPath = path;

    // First script in the folder gets the project file, so an IDE opens it as a buildable project
    // instead of a loose .cs with every Aver.Scripting symbol underlined red.
    const std::string csproj = dir + "\\" + kCsprojName;
    if (!fileExists(csproj)) {
        if (writeFileText(csproj, csprojText(scriptingProjectReference(dir)))) {
            if (outCsproj) *outCsproj = true;
        } else {
            AVER_WARN("[Editor] script written, but could not create {}", csproj);
        }
    }
    AVER_INFO("[Editor] new C# script: {}", path);
    return true;
}

} // namespace aver::editor
