// <auto-generated/>
//
// EDITOR-OWNED FILE. Everything between the region markers below is generated and rewritten by the Aver
// editor when you drag a model in the actor viewport and save. Do not hand-edit inside the region: your
// changes there will be overwritten. Hand-written behaviour for this actor lives in Car.cs.
//
// The editor only ever rewrites text IT generated (the coordinate literals below, matched by each model's
// ObjectId). It never touches Car.cs, never touches this header, and never touches anything outside the
// region markers. See docs/DESIGNER_REWRITE.md for the exact rule.

using Aver.Framework;

namespace Sample.Game;

partial class Car
{
    // <aver-generated region="models" schema="1"> DO NOT EDIT — the editor owns everything to </aver-generated>.
    [Model] public ModelHandle Body    { get; private set; }
    [Model] public ModelHandle WheelFL { get; private set; }
    [Model] public ModelHandle WheelFR { get; private set; }
    [Model] public ModelHandle WheelRL { get; private set; }
    [Model] public ModelHandle WheelRR { get; private set; }

    protected override void BuildModels(ActorBuilder b)
    {
        Body    = b.Place(0x9E1C6A4B7F0D2233UL, "Content/Meshes/CarBody.ocmesh", material: "M_CarPaint", pos: (0f, 0f, 45f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
        WheelFL = b.Place(0x3A77B0110C55E9F2UL, "Content/Meshes/Wheel.ocmesh", material: "M_Rubber", pos: (120f, 80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
        WheelFR = b.Place(0x5D2E44819AB13C60UL, "Content/Meshes/Wheel.ocmesh", material: "M_Rubber", pos: (120f, -80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
        WheelRL = b.Place(0x11C0FE73D6A48825UL, "Content/Meshes/Wheel.ocmesh", material: "M_Rubber", pos: (-120f, 80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
        WheelRR = b.Place(0x77AA5591E2440BD1UL, "Content/Meshes/Wheel.ocmesh", material: "M_Rubber", pos: (-120f, -80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
    }
    // </aver-generated>
}
