// <auto-generated/>
//
// EDITOR-OWNED FILE. The editor rewrites everything between the region markers below; do not
// hand-edit inside them. Hand-written behaviour for this actor lives in Car.cs.

using Aver.Framework;

namespace Sample.Game;

partial class Car
{
    // <aver-generated region="models" schema="1"> DO NOT EDIT — the editor owns everything to </aver-generated>.
    [Model] public ModelHandle Body    { get; private set; }
    [Model] public ModelHandle WheelFL { get; private set; }
    [Model] public ModelHandle WheelFR { get; private set; }
    [Model] public ModelHandle WheelRL { get; private set; }
    [Model] public ModelHandle WheelRR { get; private set; }

    protected override void BuildModels(ActorBuilder b)
    {
        Body    = b.Place(0x9E1C6A4B7F0D2233UL, "Content/Meshes/CarBody.ocmesh", material: "M_CarPaint", pos: (0f, 0f, 45f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
        WheelFL = b.Place(0x3A77B0110C55E9F2UL, "Content/Meshes/Wheel.ocmesh", material: "M_Rubber", pos: (120f, 80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
        WheelFR = b.Place(0x5D2E44819AB13C60UL, "Content/Meshes/Wheel.ocmesh", material: "M_Rubber", pos: (120f, -80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
        WheelRL = b.Place(0x11C0FE73D6A48825UL, "Content/Meshes/Wheel.ocmesh", material: "M_Rubber", pos: (-120f, 80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
        WheelRR = b.Place(0x77AA5591E2440BD1UL, "Content/Meshes/Wheel.ocmesh", material: "M_Rubber", pos: (-120f, -80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
    }
    // </aver-generated>
}
