// The Roslyn actor-script backend, checked against the built-in scanner.
// Skips loudly when averdesign is not staged.
#include "aver/formats/ActorScript.hpp"
#include "aver/formats/AverDesign.hpp"
#include "aver/core/Log.hpp"
#include "aver/platform/FileSystem.hpp"

#include <cmath>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

using namespace aver;

static int g_failures = 0;
static int g_skipped = 0;

// Records one assertion. Counts a failure and logs it when the condition is false.
static void check(bool cond, const std::string& what) {
    if (cond) { AVER_INFO("  ok    {}", what); return; }
    ++g_failures;
    AVER_ERROR("  FAIL  {}", what);
}

// True when two floats agree to 1e-4.
static bool near(f32 a, f32 b) { return std::fabs(a - b) <= 1.0e-4f; }

static std::filesystem::path g_tmp;

// Writes a source file into the test's own directory and returns its path.
static std::string writeTemp(const std::string& name, const std::string& text) {
    const std::filesystem::path p = g_tmp / name;
    std::ofstream os(p, std::ios::binary | std::ios::trunc);
    os.write(text.data(), static_cast<std::streamsize>(text.size()));
    os.close();
    return p.string();
}

// A generated region exactly as the editor writes it. Conforming, so both backends read it.
static const char* kConforming = R"(// <auto-generated/>
using Aver.Framework;

namespace Sample.Game;

partial class Rig
{
    // <aver-generated region="models" schema="1"> DO NOT EDIT </aver-generated>.
    [Model] public ModelHandle Body { get; private set; }
    [Model] public ModelHandle Arm  { get; private set; }

    protected override void BuildModels(ActorBuilder b)
    {
        Body = b.Place(0x9E1C6A4B7F0D2233UL, "Content/Meshes/Body.ocmesh", material: "M_Steel", pos: (0f, 0f, 45f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));
        Arm  = b.Place(0x3A77B0110C55E9F2UL, "Content/Meshes/Arm.ocmesh", material: "M_Rubber", pos: (-120f, 80f, 20.5f), rot: (0f, 90f, 0f), scale: (2f, 1f, 1f));
    }
    // </aver-generated>
}
)";

// Runs every Roslyn backend check. Returns 1 if any failed.
int main() {
    AVER_INFO("=== the Roslyn actor-script backend ===");

    fmt::setAverDesignPath(executableDir() + "\\Tools\\averdesign.exe");

    if (!fmt::averDesignAvailable()) {
        AVER_WARN("=== SKIPPED: averdesign is not staged at {} ===", fmt::averDesignPath());
        AVER_WARN("=== nothing about the Roslyn backend was checked in this run ===");
        return 0;
    }

    std::error_code ec;
    g_tmp = std::filesystem::temp_directory_path(ec) / "aver-roslyn-test";
    std::filesystem::remove_all(g_tmp, ec);
    std::filesystem::create_directories(g_tmp, ec);
    if (ec) { AVER_ERROR("could not make a temp directory"); return 1; }

    {
        AVER_INFO("-- the two backends agree on a conforming file --");
        const std::string path = writeTemp("Rig.Designer.cs", kConforming);
        const fmt::ActorScript scanned = fmt::parseActorScript(kConforming);
        check(scanned.status == fmt::ActorParseStatus::Ok, "the built-in scanner reads it");
        check(scanned.backend == fmt::ActorParserBackend::Builtin, "and says so");

        fmt::RoslynParse rp;
        std::string why;
        const bool ran = fmt::parseActorFileRoslyn(path, rp, &why);
        check(ran, "averdesign runs" + (ran ? std::string() : ": " + why));
        if (!ran) { AVER_ERROR("cannot continue without the tool"); return 1; }

        check(rp.script.backend == fmt::ActorParserBackend::Roslyn, "and the result says Roslyn");
        check(rp.script.status == fmt::ActorParseStatus::Ok, "Roslyn reads it too");
        check(rp.script.models.size() == scanned.models.size(),
              "both find the same NUMBER of placements");

        check(rp.script.regionBegin == scanned.regionBegin, "both agree where the region BEGINS");
        check(rp.script.regionEnd == scanned.regionEnd, "both agree where the region ENDS");

        const usize n = std::min(rp.script.models.size(), scanned.models.size());
        for (usize i = 0; i < n; ++i) {
            const fmt::ActorModel& a = scanned.models[i];
            const fmt::ActorModel& b = rp.script.models[i];
            char what[128];
            std::snprintf(what, sizeof what, "placement %zu: ", i);
            const std::string w = what;
            check(a.objectId == b.objectId, w + "the same 64-bit object id");
            check(a.property == b.property, w + "the same property name");
            check(a.meshPath == b.meshPath, w + "the same mesh path");
            check(a.material == b.material, w + "the same material");
            bool posSame = true, rotSame = true, sclSame = true;
            for (int k = 0; k < 3; ++k) {
                posSame = posSame && near(a.pos[k], b.pos[k]);
                rotSame = rotSame && near(a.rot[k], b.rot[k]);
                sclSame = sclSame && near(a.scale[k], b.scale[k]);
            }
            check(posSame, w + "the same position");
            check(rotSame, w + "the same rotation");
            check(sclSame, w + "the same scale");
            check(a.begin == b.begin && a.end == b.end, w + "the same byte span for the statement");
        }
    }

    {
        AVER_INFO("-- byte spans survive non-ASCII text above the region --");
        std::string src = kConforming;
        const std::string comment =
            "// Rotationsträger, \xC2\xB5-Antrieb, \xE2\x80\x94 and an em dash \xF0\x9F\x9A\x97\n";
        src.insert(src.find("using Aver.Framework;"), comment);
        const std::string path = writeTemp("Umlaut.Designer.cs", src);

        const fmt::ActorScript scanned = fmt::parseActorScript(src);
        fmt::RoslynParse rp;
        std::string why;
        check(fmt::parseActorFileRoslyn(path, rp, &why), "averdesign reads a file with multi-byte text");
        check(scanned.status == fmt::ActorParseStatus::Ok, "the scanner reads it too");
        check(rp.script.models.size() == scanned.models.size(), "both still find every placement");
        if (!rp.script.models.empty() && !scanned.models.empty()) {
            check(rp.script.models[0].begin == scanned.models[0].begin,
                  "and the spans STILL agree -- the char-to-byte conversion held");
            const fmt::ActorModel& m = rp.script.models[0];
            const bool inRange = m.end <= src.size() && m.begin < m.end;
            check(inRange, "the span is inside the file");
            if (inRange) {
                const std::string slice = src.substr(m.begin, m.end - m.begin);
                check(slice.rfind("Body", 0) == 0 && slice.back() == ';',
                      "and it names the whole statement, semicolon included");
            }
        }
    }

    // One awkward placement the built-in scanner may or may not accept.
    struct Case {
        const char* what;
        const char* placement;
        bool expectValues;    // can Roslyn recover the coordinates, or only the row?
        bool scannerDeclines; // does this leave the locked grammar, or merely look like it does?
    };
    const Case cases[] = {
        {"named arguments in a different order",
         R"(        Body = b.Place(0x9E1C6A4B7F0D2233UL, "Content/Meshes/Body.ocmesh", scale: (1f, 1f, 1f), pos: (0f, 0f, 45f), rot: (0f, 0f, 0f), material: "M_Steel");)",
         true, true},
        {"an omitted argument",
         R"(        Body = b.Place(0x9E1C6A4B7F0D2233UL, "Content/Meshes/Body.ocmesh", pos: (0f, 0f, 45f));)",
         true, true},
        {"integer literals where floats are expected",
         R"(        Body = b.Place(0x9E1C6A4B7F0D2233UL, "Content/Meshes/Body.ocmesh", material: "M_Steel", pos: (0, 0, 45), rot: (0, 0, 0), scale: (1, 1, 1));)",
         true, true},
        {"line breaks inside the call",
         "        Body = b.Place(0x9E1C6A4B7F0D2233UL,\n"
         "                       \"Content/Meshes/Body.ocmesh\",\n"
         "                       material: \"M_Steel\",\n"
         "                       pos: (0f, 0f, 45f),\n"
         "                       rot: (0f, 0f, 0f),\n"
         "                       scale: (1f, 1f, 1f));",
         true, false},
    };

    for (const Case& c : cases) {
        AVER_INFO("-- {} --", c.what);
        std::string src = kConforming;
        const usize lineStart = src.find("        Body = b.Place");
        const usize lineEnd = src.find('\n', lineStart);
        src = src.substr(0, lineStart) + c.placement + src.substr(lineEnd);

        const fmt::ActorScript scanned = fmt::parseActorScript(src);
        if (c.scannerDeclines) {
            check(scanned.status == fmt::ActorParseStatus::Malformed,
                  "the built-in scanner declines it as Malformed");
        } else {
            check(scanned.status == fmt::ActorParseStatus::Ok,
                  "the built-in scanner reads it after all -- so the two must AGREE, not merely both work");
        }

        char name[64];
        std::snprintf(name, sizeof name, "Case%d.Designer.cs", static_cast<int>(&c - cases));
        const std::string path = writeTemp(name, src);

        fmt::RoslynParse rp;
        std::string why;
        const bool ran = fmt::parseActorFileRoslyn(path, rp, &why);
        check(ran, std::string("averdesign runs on it") + (ran ? "" : ": " + why));
        if (!ran) continue;
        check(rp.script.status == fmt::ActorParseStatus::Ok, "and Roslyn reads the region");
        check(rp.script.models.size() == 2, "finding BOTH placements, awkward one included");

        if (c.expectValues && !rp.script.models.empty()) {
            const fmt::ActorModel& m = rp.script.models[0];
            check(m.objectId == 0x9E1C6A4B7F0D2233ULL, "with the right object id");
            check(m.meshPath == "Content/Meshes/Body.ocmesh", "and the right mesh");
            check(near(m.pos[0], 0.0f) && near(m.pos[1], 0.0f) && near(m.pos[2], 45.0f),
                  "and the right position, whatever order it was written in");
        }

        if (!c.scannerDeclines && scanned.status == fmt::ActorParseStatus::Ok &&
            !scanned.models.empty() && !rp.script.models.empty()) {
            check(scanned.models[0].begin == rp.script.models[0].begin &&
                  scanned.models[0].end   == rp.script.models[0].end,
                  "and both backends give the SAME span for a call broken across lines");
            check(near(scanned.models[0].pos[2], rp.script.models[0].pos[2]),
                  "and the same coordinates");
        }
    }

    {
        AVER_INFO("-- class facts --");
        const char* src = R"(using Aver.Framework;
namespace Demo;

[AverClass("AN_Crate")]
public sealed class Crate : AverActor
{
    public static void Configure(ClassBuilder b) => b.Mesh("Meshes/cube.ocmesh", "M_Wood");
}

[AverClass("AN_Hero")]
public sealed class Hero : AverCharacter
{
    public float Height = 180f;
    public float Radius = 34f;
    public override void OnBeginPlay(BeginReason r) { EyeHeight = 165f; }
}
)";
        const std::string path = writeTemp("Facts.cs", src);
        fmt::RoslynParse rp;
        std::string why;
        check(fmt::parseActorFileRoslyn(path, rp, &why), "averdesign reads a plain actor file");
        check(rp.script.status == fmt::ActorParseStatus::NoRegion, "which has no generated region");
        check(rp.classes.size() == 2, "and declares two actors");
        if (rp.classes.size() == 2) {
            check(rp.classes[0].className == "AN_Crate", "the first is named by its attribute");
            check(rp.classes[0].typeName == "Crate", "and knows its C# type name");
            check(rp.classes[0].kind == fmt::ActorKind::Actor, "and is classified from its base");
            check(rp.classes[0].hasMesh && rp.classes[0].meshPath == "Meshes/cube.ocmesh",
                  "with the mesh its Configure declares");
            check(rp.classes[0].material == "M_Wood", "and the material beside it");

            check(rp.classes[1].kind == fmt::ActorKind::Character, "the second is a Character");
            check(near(rp.classes[1].capsuleHeight, 180.0f), "with its capsule height");
            check(near(rp.classes[1].capsuleRadius, 34.0f), "and radius");
            check(near(rp.classes[1].eyeHeight, 165.0f), "and an eye height set inside a method body");

            const fmt::ActorValueSpan& hs = rp.classes[1].capsuleHeightSpan;
            check(hs.valid(), "the height carries a span");
            if (hs.valid() && hs.end <= std::string_view(src).size())
                check(std::string_view(src).substr(hs.begin, hs.end - hs.begin) == "180f",
                      "and that span names exactly the literal it read");
        }
    }

    std::filesystem::remove_all(g_tmp, ec);

    if (g_failures == 0 && g_skipped == 0) AVER_INFO("=== all Roslyn backend tests passed ===");
    else if (g_failures == 0)              AVER_WARN("=== passed, {} skipped ===", g_skipped);
    else                                   AVER_ERROR("=== {} Roslyn check(s) FAILED ===", g_failures);
    return g_failures == 0 ? 0 : 1;
}
