// Reading and rewriting a `.Designer.cs`: the actor editor's half of the file. Covers the class
// scanner, the class-defaults rewriter, the generated-region parser and its rewriter.
#include "aver/formats/ActorScript.hpp"
#include "aver/core/Log.hpp"

#include <cmath>
#include <string>

using namespace aver;

static int g_failures = 0;

// Logs one assertion and counts the failures.
static void check(bool cond, const std::string& what) {
    if (cond) { AVER_INFO("  ok    {}", what); return; }
    ++g_failures;
    AVER_ERROR("  FAIL  {}", what);
}

// True when two floats are within eps.
static bool near(f32 a, f32 b, f32 eps = 1e-4f) { return std::fabs(a - b) <= eps; }

// A generated region holding two placements.
static const char* kCar =
    "// <auto-generated/>\n"
    "using Aver.Framework;\n"
    "\n"
    "namespace Sample.Game;\n"
    "\n"
    "partial class Car\n"
    "{\n"
    "    // <aver-generated region=\"models\" schema=\"1\"> DO NOT EDIT\n"
    "    [Model] public ModelHandle Body    { get; private set; }\n"
    "    [Model] public ModelHandle WheelFL { get; private set; }\n"
    "\n"
    "    protected override void BuildModels(ActorBuilder b)\n"
    "    {\n"
    "        Body    = b.Place(0x9E1C6A4B7F0D2233UL, \"Content/Meshes/CarBody.ocmesh\", material: \"M_CarPaint\", pos: (0f, 0f, 45f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
    "        WheelFL = b.Place(0x3A77B0110C55E9F2UL, \"Meshes/Wheel.ocmesh\", material: \"M_Rubber\", pos: (120f, 80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
    "    }\n"
    "    // </aver-generated>\n"
    "}\n";


// Checks parseActorClass on actors that declare their mesh, camera or light on the class itself.
static void testClassLevelActor() {
    AVER_INFO("=== an actor that declares itself ===");

    static const char* kGun =
        "using Aver.Framework;\n"
        "namespace SkyForge;\n"
        "\n"
        "[AverClass(\"AN_Gun\")]\n"
        "public sealed class Gun : AverActor\n"
        "{\n"
        "    public static void Configure(ClassBuilder b) => b.Mesh(\"Meshes/cube.ocmesh\");\n"
        "}\n";

    const fmt::ActorClassInfo g = fmt::parseActorClass(kGun);
    check(g.className == "AN_Gun", "the bound name is read from [AverClass]");
    check(g.hasMesh, "a class-level mesh is found");
    check(g.meshPath == "Meshes/cube.ocmesh", "with its path");
    check(g.anything(), "so the file is previewable");
    check(fmt::parseActorScript(kGun).status == fmt::ActorParseStatus::NoRegion,
          "and no generated region, which is legal");

    static const char* kWithMat =
        "[AverClass(\"AN_Crate\")]\n"
        "public sealed class Crate : AverActor {\n"
        "    public static void Configure(ClassBuilder b) {\n"
        "        b.Mesh(\"Meshes/box.ocmesh\", \"M_Crate\");\n"
        "        b.Ticks(TickGroup.PostPhysics);\n"
        "    }\n"
        "}\n";
    const fmt::ActorClassInfo c = fmt::parseActorClass(kWithMat);
    check(c.hasMesh && c.material == "M_Crate", "a block-bodied Configure is read too, with material");

    static const char* kMode =
        "[AverGameMode(\"AN_FpsGameMode\", DefaultPawnClass = \"AN_FpsCharacter\")]\n"
        "public sealed class FpsGameMode : AverGameMode { }\n";
    check(fmt::parseActorClass(kMode).className == "AN_FpsGameMode",
          "[AverGameMode] carries a bound name too");

    static const char* kRig =
        "[AverClass(\"AN_Rig\")]\n"
        "public sealed class Rig : AverPawn {\n"
        "    public static void Configure(ClassBuilder b) {\n"
        "        b.Camera(70f, 5f, 100000f);\n"
        "        b.PointLight(1200f, 800f);\n"
        "    }\n"
        "}\n";
    const fmt::ActorClassInfo r = fmt::parseActorClass(kRig);
    check(r.hasCamera && !r.hasMesh, "a camera is recorded without a mesh");
    check(near(r.cameraFovDeg, 70.0f) && near(r.cameraFarCm, 100000.0f), "with its numbers");
    check(r.hasPointLight && near(r.lightIntensityLux, 1200.0f), "and so is a point light");
    check(r.anything(), "so a camera-only actor is still worth opening");

    static const char* kConst =
        "[AverClass(\"AN_C\")]\n"
        "public sealed class C : AverActor {\n"
        "    public static void Configure(ClassBuilder b) => b.Camera(Fov, 1f, 2f);\n"
        "}\n";
    check(fmt::parseActorClass(kConst).hasCamera, "a non-literal argument still declares the camera");

    static const char* kPlain = "public static class Helpers { public static int Add(int a) => a; }\n";
    check(!fmt::parseActorClass(kPlain).anything(), "a plain helper class declares nothing");
}


// Checks rewriteActorClass: edited values are written back through the spans they were read from.
static void testClassDefaultsRewrite() {
    AVER_INFO("=== editing class defaults ===");

    static const char* kSrc =
        "using Aver.Framework;\n"
        "namespace Game;\n"
        "\n"
        "[AverClass(\"Hero\")]\n"
        "public sealed class Hero : AverCharacter\n"
        "{\n"
        "    public static void Configure(ClassBuilder b) => b.Camera(70f, 5f, 100000f);\n"
        "    public override void OnBeginPlay(BeginReason r)\n"
        "    {\n"
        "        Height    = 180f;   // a person, in centimetres\n"
        "        Radius    = 34f;\n"
        "        EyeHeight = 165f;\n"
        "    }\n"
        "}\n"
        "\n"
        "[AverClass(\"Prop\")]\n"
        "public sealed class Prop : AverActor\n"
        "{\n"
        "    public static void Configure(ClassBuilder b) => b.Mesh(\"Meshes/crate.ocmesh\", \"M_Wood\");\n"
        "    public int Height = 999;\n"
        "}\n";

    std::vector<fmt::ActorClassInfo> all = fmt::parseActorClasses(kSrc);
    check(all.size() == 2, "two classes");
    if (all.size() != 2) return;

    check(all[0].kind == fmt::ActorKind::Character, "the first is a Character");
    check(near(all[0].capsuleHeight, 180.0f) && near(all[0].capsuleRadius, 34.0f), "with its capsule read");
    check(all[0].capsuleHeightSpan.valid(), "and a span for the height");
    check(all[1].hasMesh && all[1].material == "M_Wood", "the second declares a mesh and material");

    const std::string src(kSrc);
    check(src.substr(all[0].capsuleHeightSpan.begin,
                     all[0].capsuleHeightSpan.end - all[0].capsuleHeightSpan.begin) == "180f",
          "the height span covers exactly the literal");
    check(src.substr(all[1].meshPathSpan.begin,
                     all[1].meshPathSpan.end - all[1].meshPathSpan.begin) == "Meshes/crate.ocmesh",
          "the mesh span covers the path WITHOUT its quotes");

    AVER_INFO("=== writing them back ===");
    {
        fmt::ActorClassInfo hero = all[0];
        hero.capsuleHeight = 195.0f;
        hero.eyeHeight = 178.0f;
        hero.cameraFovDeg = 90.0f;

        std::string out, err;
        check(fmt::rewriteActorClass(kSrc, hero, out, &err), "it rewrites: " + err);
        check(out.find("Height    = 195f;") != std::string::npos, "the height is written");
        check(out.find("EyeHeight = 178f;") != std::string::npos, "and the eye height");
        check(out.find("b.Camera(90f, 5f, 100000f)") != std::string::npos,
              "and one camera argument, leaving the other two alone");
        check(out.find("Radius    = 34f;") != std::string::npos, "an untouched field is untouched");
        check(out.find("// a person, in centimetres") != std::string::npos, "the trailing comment survives");

        check(out.find("public int Height = 999;") != std::string::npos,
              "a same-named field in ANOTHER class is not touched");
        check(out.find("[AverClass(\"Prop\")]") != std::string::npos, "and that class still stands");
    }

    AVER_INFO("=== strings, idempotence and refusals ===");
    {
        fmt::ActorClassInfo prop = all[1];
        prop.meshPath = "Meshes/barrel.ocmesh";
        prop.material = "M_Metal";
        std::string out, err;
        check(fmt::rewriteActorClass(kSrc, prop, out, &err), "a string value rewrites");
        check(out.find("b.Mesh(\"Meshes/barrel.ocmesh\", \"M_Metal\")") != std::string::npos,
              "both literals are replaced, quotes intact");
        check(out.find("Height    = 180f;") != std::string::npos, "the character is untouched by it");

        std::string same;
        check(fmt::rewriteActorClass(kSrc, all[0], same, &err) && same == src,
              "rewriting with the values as read is byte-identical");

        fmt::ActorClassInfo empty;
        std::string untouched;
        check(fmt::rewriteActorClass(kSrc, empty, untouched, &err) && untouched == src,
              "a class carrying no spans leaves the file alone");
    }

    AVER_INFO("=== values that cannot be written back ===");
    {
        static const char* kConst =
            "[AverClass(\"C\")]\n"
            "public sealed class C : AverActor {\n"
            "    public static void Configure(ClassBuilder b) => b.Camera(DefaultFov, 1f, 2f);\n"
            "}\n";
        const fmt::ActorClassInfo c = fmt::parseActorClass(kConst);
        check(c.hasCamera, "the camera is still recognised as declared");
        check(!c.cameraSpan[0].valid(), "but its first argument has no span, so nothing offers to edit it");
        check(c.cameraSpan[1].valid(), "while the literals after it do");
    }
}

// rewriteActorClasses: every class rewritten in one pass, and mesh/material paths re-escaped.
static void testMultiClassRewriteAndEscaping() {
    AVER_INFO("=== rewriting every class at once ===");

    static const char* kTwo =
        "using Aver.Framework;\n"
        "namespace Game;\n"
        "\n"
        "[AverClass(\"Hero\")]\n"
        "public sealed class Hero : AverCharacter\n"
        "{\n"
        "    public static void Configure(ClassBuilder b) => b.Camera(70f, 5f, 100000f);\n"
        "    public override void OnBeginPlay(BeginReason r) { Height = 180f; }\n"
        "}\n"
        "\n"
        "[AverClass(\"Prop\")]\n"
        "public sealed class Prop : AverActor\n"
        "{\n"
        "    public static void Configure(ClassBuilder b) => b.Mesh(\"Meshes/crate.ocmesh\", \"M_Wood\");\n"
        "}\n";

    std::vector<fmt::ActorClassInfo> all = fmt::parseActorClasses(kTwo);
    check(all.size() == 2, "two classes");
    if (all.size() != 2) return;

    // THE REGRESSION: shrink the first class's value so the text gets SHORTER, which is what makes
    // the second class's spans -- unchanged, still measured against the original text -- land on
    // the wrong bytes if a caller chains rewriteActorClass instead of using the batch entry point.
    fmt::ActorClassInfo hero = all[0];
    hero.capsuleHeight = 9.0f;   // "180f" (4 bytes) -> "9f" (2 bytes): the text shrinks by 2

    std::string out, err;
    check(fmt::rewriteActorClasses(kTwo, {hero, all[1]}, out, &err),
          "rewriting both classes together: " + err);
    check(out.find("Height = 9f;") != std::string::npos, "the shrunk value lands correctly");
    check(out.find("b.Mesh(\"Meshes/crate.ocmesh\", \"M_Wood\")") != std::string::npos,
          "and the SECOND class's untouched mesh call is intact -- not spliced by class 0's shift");
    check(out.find("[AverClass(\"Prop\")]") != std::string::npos, "its attribute still stands");

    // The chained (wrong) way, for contrast: this is what save() used to do, and it must actually
    // reproduce the corruption or this test would not be exercising the bug it exists for.
    std::string chained, chainedNext;
    fmt::rewriteActorClass(kTwo, hero, chained, &err);
    fmt::rewriteActorClass(chained, all[1], chainedNext, &err);
    check(chainedNext.find("b.Mesh(\"Meshes/crate.ocmesh\", \"M_Wood\")") == std::string::npos,
          "confirms the bug: chaining corrupts the second class's mesh call");

    AVER_INFO("=== a path with a backslash or a quote round-trips through the C# literal ===");
    {
        fmt::ActorClassInfo prop = all[1];
        prop.meshPath = "Meshes\\Crate.ocmesh";   // a Windows-style path: one real backslash
        prop.material = "M_\"Weird\"";            // a quote, to be thorough
        std::string escaped, escErr;
        check(fmt::rewriteActorClass(kTwo, prop, escaped, &escErr), "it rewrites: " + escErr);
        check(escaped.find("b.Mesh(\"Meshes\\\\Crate.ocmesh\", \"M_\\\"Weird\\\"\")") != std::string::npos,
              "the backslash and the quote are both escaped in the written C#");

        // And it has to round-trip: re-parsing what was written must decode back to the same value,
        // or the escaping and the parser's decoder disagree about the grammar.
        const std::vector<fmt::ActorClassInfo> reparsed = fmt::parseActorClasses(escaped);
        check(reparsed.size() == 2 && reparsed[1].meshPath == "Meshes\\Crate.ocmesh",
              "re-parsing the escaped output decodes back to the exact original path");
        check(reparsed.size() == 2 && reparsed[1].material == "M_\"Weird\"",
              "and the material too");
    }
}


// Checks that parseActorClasses classifies every shape of actor class a project produces.
static void testEveryActorShape() {
    AVER_INFO("=== every shape an actor can take ===");

    // One fixture: its source, the kind expected, and whether the actor tab should open it.
    struct Case {
        const char* what;
        const char* src;
        fmt::ActorKind kind;
        bool openable;
    };

    const Case cases[] = {
        {"a plain attributed actor",
         "using Aver.Framework;@[AverClass(\"AN_Crate\")]@public sealed class Crate : AverActor {@"
         "  public static void Configure(ClassBuilder b) => b.Mesh(\"Meshes/cube.ocmesh\");@}",
         fmt::ActorKind::Actor, true},

        {"an UNATTRIBUTED actor -- discovered by its base alone",
         "using Aver.Framework;@public sealed class Barrel : AverActor {@"
         "  public static void Configure(ClassBuilder b) => b.Mesh(\"Meshes/cube.ocmesh\");@}",
         fmt::ActorKind::Actor, true},

        {"a pawn",
         "using Aver.Framework;@[AverClass(\"AN_Drone\")]@public sealed class Drone : AverPawn {@}",
         fmt::ActorKind::Pawn, true},

        {"a character, which has a capsule and no mesh",
         "using Aver.Framework;@public sealed class Hero : AverCharacter {@"
         "  public float Height = 180f;@  public float Radius = 34f;@}",
         fmt::ActorKind::Character, true},

        {"a player controller",
         "using Aver.Framework;@public sealed class Cam : AverPlayerController {@}",
         fmt::ActorKind::PlayerController, true},

        {"a game mode",
         "using Aver.Framework;@[AverGameMode(\"AN_Rules\")]@public sealed class Rules : AverGameMode {@}",
         fmt::ActorKind::GameMode, true},

        {"a game instance",
         "using Aver.Framework;@public sealed class Save : AverGameInstance {@}",
         fmt::ActorKind::GameInstance, true},

        {"a PROJECT'S OWN pawn base, one hop from the framework's",
         "using Aver.Framework;@public class SkyForgePawn : AverPawn {@}@"
         "public sealed class Guard : SkyForgePawn {@}",
         fmt::ActorKind::Pawn, true},

        {"a class with an unrecognised base that still DECLARES a mesh",
         "using Aver.Framework;@[AverClass(\"AN_Odd\")]@public sealed class Odd : SomethingElse {@"
         "  public static void Configure(ClassBuilder b) => b.Mesh(\"Meshes/cube.ocmesh\");@}",
         fmt::ActorKind::Unknown, true},

        {"a plain helper -- no base, nothing declared, and NOT an actor",
         "namespace X;@public static class Helper {@  public static int Add(int a, int b) => a + b;@}",
         fmt::ActorKind::Unknown, false},
    };

    for (const Case& c : cases) {
        std::string src = c.src;
        for (char& ch : src) if (ch == '@') ch = 0x0A;

        const std::vector<fmt::ActorClassInfo> ks = fmt::parseActorClasses(src);

        bool openable = false;
        fmt::ActorKind best = fmt::ActorKind::Unknown;
        for (const fmt::ActorClassInfo& k : ks) {
            if (k.anything() || k.kind != fmt::ActorKind::Unknown) openable = true;
            if (k.kind != fmt::ActorKind::Unknown) best = k.kind;
        }
        if (!ks.empty() && best == fmt::ActorKind::Unknown) best = ks.back().kind;

        check(openable == c.openable, std::string(c.what) + ": the tab "
              + (c.openable ? "opens it" : "declines it"));
        if (c.openable)
            check(best == c.kind, std::string(c.what) + ": classified as "
                  + fmt::actorKindName(c.kind));
    }

    {
        std::string src =
            "using Aver.Framework;@[AverGameMode(\"AN_Mode\")]@public sealed class Mode : AverGameMode {@}@"
            "[AverClass(\"AN_Block\")]@public sealed class Block : AverActor {@"
            "  public static void Configure(ClassBuilder b) => b.Mesh(\"Meshes/cube.ocmesh\");@}@"
            "public sealed class Watcher : AverGameInstance {@}";
        for (char& ch : src) if (ch == '@') ch = 0x0A;
        const std::vector<fmt::ActorClassInfo> ks = fmt::parseActorClasses(src);
        check(ks.size() == 3, "three classes in one file are all found");
        if (ks.size() == 3) {
            check(ks[0].kind == fmt::ActorKind::GameMode, "the first is the game mode");
            check(ks[1].kind == fmt::ActorKind::Actor && ks[1].hasMesh,
                  "the second is an actor with its own mesh");
            check(ks[2].kind == fmt::ActorKind::GameInstance, "the third is the game instance");
            check(!ks[0].hasMesh && !ks[2].hasMesh, "and neither of the others claims its mesh");
        }
    }
}

// Runs every actor script test. Returns 0 when they all pass.
int main() {
    testEveryActorShape();
    testClassLevelActor();
    testClassDefaultsRewrite();
    testMultiClassRewriteAndEscaping();

    AVER_INFO("=== reading the generated region ===");
    {
        const fmt::ActorScript s = fmt::parseActorScript(kCar);
        check(s.status == fmt::ActorParseStatus::Ok, "it parses: " + s.error);
        check(s.backend == fmt::ActorParserBackend::Builtin, "through the built-in scanner");
        check(s.models.size() == 2, "two placements");
        if (s.models.size() == 2) {
            check(s.models[0].objectId == 0x9E1C6A4B7F0D2233ULL, "the full 64-bit ObjectId survives");
            check(s.models[0].property == "Body", "and the property name");
            check(s.models[0].material == "M_CarPaint", "and the material");
            check(near(s.models[0].pos[2], 45.0f), "and the coordinates");
            check(near(s.models[1].pos[0], 120.0f) && near(s.models[1].pos[1], 80.0f),
                  "of the second row too");
            check(near(s.models[1].scale[0], 1.0f), "scale defaults through as authored");
        }
    }

    AVER_INFO("=== the mesh path both halves must agree on ===");
    {
        check(fmt::canonicalMeshPath("Content/Meshes/CarBody.ocmesh") == "Meshes/CarBody.ocmesh",
              "a Content/ prefix is stripped");
        check(fmt::canonicalMeshPath("Meshes/Wheel.ocmesh") == "Meshes/Wheel.ocmesh",
              "an already-canonical path is unchanged");
        check(fmt::canonicalMeshPath("Content\\Meshes\\A.ocmesh") == "Meshes/A.ocmesh",
              "backslashes become forward slashes");
        check(fmt::canonicalMeshPath("./Content/Meshes/A.ocmesh") == "Meshes/A.ocmesh",
              "a leading ./ goes too");
        check(fmt::canonicalMeshPath("ContentPacks/Meshes/A.ocmesh") == "ContentPacks/Meshes/A.ocmesh",
              "a folder merely starting with 'Content' is left alone");
    }

    AVER_INFO("=== rewriting one row ===");
    {
        fmt::ActorScript s = fmt::parseActorScript(kCar);
        std::vector<fmt::ActorModel> edits;
        fmt::ActorModel e = s.models[0];
        e.pos[0] = 12.5f; e.pos[1] = -3.0f; e.pos[2] = 45.0f;
        e.rot[1] = 90.0f;
        edits.push_back(e);

        std::string out, err;
        check(fmt::rewriteActorScript(kCar, edits, out, &err), "it rewrites: " + err);
        check(out.find("pos: (12.5f, -3f, 45f)") != std::string::npos, "the dragged position is written");
        check(out.find("rot: (0f, 90f, 0f)") != std::string::npos, "and the rotation");

        check(out.find("WheelFL = b.Place(0x3A77B0110C55E9F2UL, \"Meshes/Wheel.ocmesh\", "
                       "material: \"M_Rubber\", pos: (120f, 80f, 20f)") != std::string::npos,
              "the other placement is byte-identical");

        check(out.find("// <auto-generated/>") != std::string::npos, "the header survives");
        check(out.find("namespace Sample.Game;") != std::string::npos, "the namespace survives");
        check(out.find("partial class Car") != std::string::npos, "the class header survives");
        check(out.find("[Model] public ModelHandle Body") != std::string::npos,
              "the property declarations survive");

        check(out.find("\"Content/Meshes/CarBody.ocmesh\", material: \"M_CarPaint\"") != std::string::npos,
              "the mesh and material are not rewritten by a coordinate save");
    }

    AVER_INFO("=== idempotence and no-ops ===");
    {
        fmt::ActorScript s = fmt::parseActorScript(kCar);
        std::string once, twice, err;
        check(fmt::rewriteActorScript(kCar, s.models, once, &err), "rewriting with what was read");
        check(once == std::string(kCar), "an unedited save changes NOTHING");
        check(fmt::rewriteActorScript(once, s.models, twice, &err) && twice == once,
              "and doing it twice changes nothing again");

        fmt::ActorModel ghost;
        ghost.objectId = 0xDEADBEEFULL;
        std::string out;
        check(fmt::rewriteActorScript(kCar, {ghost}, out, &err) && out == std::string(kCar),
              "an unknown ObjectId is ignored rather than appended");
    }

    AVER_INFO("=== what the scanner declines ===");
    {
        std::string out, err;

        const fmt::ActorScript none = fmt::parseActorScript("class Plain {}\n");
        check(none.status == fmt::ActorParseStatus::NoRegion, "a file with no region reports NoRegion");
        check(!fmt::rewriteActorScript("class Plain {}\n", {}, out, &err), "and cannot be rewritten");

        const char* newer =
            "// <aver-generated region=\"models\" schema=\"2\">\n"
            "// </aver-generated>\n";
        const fmt::ActorScript s2 = fmt::parseActorScript(newer);
        check(s2.status == fmt::ActorParseStatus::UnknownSchema, "an unknown schema is refused");
        check(s2.error.find("schema") != std::string::npos, "and says so");

        const fmt::ActorScript unterminated =
            fmt::parseActorScript("// <aver-generated region=\"models\" schema=\"1\">\nx\n");
        check(unterminated.status == fmt::ActorParseStatus::Malformed, "an unclosed region is Malformed");

        const char* reordered =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x1UL, \"m.ocmesh\", pos: (0f, 0f, 0f), material: \"M\", rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        const fmt::ActorScript ro = fmt::parseActorScript(reordered);
        check(ro.status == fmt::ActorParseStatus::Malformed,
              "reordered named arguments are declined, not misread");

        const char* expression =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x1UL, \"m.ocmesh\", material: \"M\", pos: (Offset + 1f, 0f, 0f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        check(fmt::parseActorScript(expression).status == fmt::ActorParseStatus::Malformed,
              "a coordinate written as an expression is declined");

        const char* noSuffix =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x1UL, \"m.ocmesh\", material: \"M\", pos: (0, 0, 0), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        check(fmt::parseActorScript(noSuffix).status == fmt::ActorParseStatus::Malformed,
              "a coordinate missing its f suffix is declined");

        const char* dupes =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x7UL, \"m.ocmesh\", material: \"M\", pos: (0f, 0f, 0f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "        B = b.Place(0x7UL, \"m.ocmesh\", material: \"M\", pos: (1f, 0f, 0f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        const fmt::ActorScript dup = fmt::parseActorScript(dupes);
        check(dup.status == fmt::ActorParseStatus::Malformed, "duplicate ObjectIds are refused");
        check(dup.error.find("key") != std::string::npos, "and the reason names the key");
    }

    AVER_INFO("=== a marker that is not a marker ===");
    {
        const char* decoy =
            "class X { string s = \"// <aver-generated region=\\\"models\\\" schema=\\\"1\\\">\"; }\n";
        check(fmt::parseActorScript(decoy).status == fmt::ActorParseStatus::NoRegion,
              "the marker text inside a string literal does not open a region");
    }

    if (g_failures == 0) AVER_INFO("=== all actor script tests passed ===");
    else                 AVER_ERROR("=== {} FAILED ===", g_failures);
    return g_failures == 0 ? 0 : 1;
}
