// Reading and rewriting a `.Designer.cs` — the actor editor's half of the file.
//
// Every property below is one a viewport and a gizmo depend on and neither can show you: a drag
// writes a number into somebody's source, and the ways that goes wrong are all silent. The wrong row
// moves. A neighbouring model loses a digit. The hand-written half is touched. A file the scanner
// should have declined is half-rewritten instead.
#include "aver/formats/ActorScript.hpp"
#include "aver/core/Log.hpp"

#include <cmath>
#include <string>

using namespace aver;

static int g_failures = 0;

static void check(bool cond, const std::string& what) {
    if (cond) { AVER_INFO("  ok    {}", what); return; }
    ++g_failures;
    AVER_ERROR("  FAIL  {}", what);
}

static bool near(f32 a, f32 b, f32 eps = 1e-4f) { return std::fabs(a - b) <= eps; }

// The real sample from the tree, trimmed to what matters.
static const char* kCar =
    "// <auto-generated/>\n"
    "using Aver.Framework;\n"
    "\n"
    "namespace Sample.Game;\n"
    "\n"
    "partial class Car\n"
    "{\n"
    "    // <aver-generated region=\"models\" schema=\"1\"> DO NOT EDIT\n"
    "    [Model] public ModelHandle Body    { get; private set; }\n"
    "    [Model] public ModelHandle WheelFL { get; private set; }\n"
    "\n"
    "    protected override void BuildModels(ActorBuilder b)\n"
    "    {\n"
    "        Body    = b.Place(0x9E1C6A4B7F0D2233UL, \"Content/Meshes/CarBody.ocmesh\", material: \"M_CarPaint\", pos: (0f, 0f, 45f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
    "        WheelFL = b.Place(0x3A77B0110C55E9F2UL, \"Meshes/Wheel.ocmesh\", material: \"M_Rubber\", pos: (120f, 80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
    "    }\n"
    "    // </aver-generated>\n"
    "}\n";


// THE COMMON ACTOR: one mesh declared on the class, no designer region at all.
//
// This is what most actors in most games are, and every actor in the SkyForge template. An editor
// that only understood placements would show an empty view for all of them, which is the difference
// between an actor editor and a car editor.
static void testClassLevelActor() {
    AVER_INFO("=== an actor that declares itself ===");

    static const char* kGun =
        "using Aver.Framework;\n"
        "namespace SkyForge;\n"
        "\n"
        "[AverClass(\"BP_Gun\")]\n"
        "public sealed class Gun : AverActor\n"
        "{\n"
        "    public static void Configure(ClassBuilder b) => b.Mesh(\"Meshes/cube.ocmesh\");\n"
        "}\n";

    const fmt::ActorClassInfo g = fmt::parseActorClass(kGun);
    check(g.className == "BP_Gun", "the bound name is read from [AverClass]");
    check(g.hasMesh, "a class-level mesh is found");
    check(g.meshPath == "Meshes/cube.ocmesh", "with its path");
    check(g.anything(), "so the file is previewable");
    // And it has NO designer region, which is not an error -- it is the ordinary case.
    check(fmt::parseActorScript(kGun).status == fmt::ActorParseStatus::NoRegion,
          "and no generated region, which is legal");

    // A mesh WITH a material.
    static const char* kWithMat =
        "[AverClass(\"BP_Crate\")]\n"
        "public sealed class Crate : AverActor {\n"
        "    public static void Configure(ClassBuilder b) {\n"
        "        b.Mesh(\"Meshes/box.ocmesh\", \"M_Crate\");\n"
        "        b.Ticks(TickGroup.PostPhysics);\n"
        "    }\n"
        "}\n";
    const fmt::ActorClassInfo c = fmt::parseActorClass(kWithMat);
    check(c.hasMesh && c.material == "M_Crate", "a block-bodied Configure is read too, with material");

    // A GAME MODE is an actor as far as the editor is concerned. Recognising only [AverClass] would
    // open some of a project's files and not others, for no reason a user could see.
    static const char* kMode =
        "[AverGameMode(\"BP_FpsGameMode\", DefaultPawnClass = \"BP_FpsCharacter\")]\n"
        "public sealed class FpsGameMode : AverGameMode { }\n";
    check(fmt::parseActorClass(kMode).className == "BP_FpsGameMode",
          "[AverGameMode] carries a bound name too");

    // A CAMERA and a LIGHT are recorded but not drawn. An actor that is only a light previews as an
    // empty view, and empty is indistinguishable from broken unless something says otherwise.
    static const char* kRig =
        "[AverClass(\"BP_Rig\")]\n"
        "public sealed class Rig : AverPawn {\n"
        "    public static void Configure(ClassBuilder b) {\n"
        "        b.Camera(70f, 5f, 100000f);\n"
        "        b.PointLight(1200f, 800f);\n"
        "    }\n"
        "}\n";
    const fmt::ActorClassInfo r = fmt::parseActorClass(kRig);
    check(r.hasCamera && !r.hasMesh, "a camera is recorded without a mesh");
    check(near(r.cameraFovDeg, 70.0f) && near(r.cameraFarCm, 100000.0f), "with its numbers");
    check(r.hasPointLight && near(r.lightIntensityLux, 1200.0f), "and so is a point light");
    check(r.anything(), "so a camera-only actor is still worth opening");

    // A value that is not a plain literal still means the feature IS declared. The number is what
    // could not be read, not the fact -- and refusing the whole declaration over one constant would
    // make the preview lie about what the actor has.
    static const char* kConst =
        "[AverClass(\"BP_C\")]\n"
        "public sealed class C : AverActor {\n"
        "    public static void Configure(ClassBuilder b) => b.Camera(Fov, 1f, 2f);\n"
        "}\n";
    check(fmt::parseActorClass(kConst).hasCamera, "a non-literal argument still declares the camera");

    // A plain class with none of it declares nothing, and the editor leaves it to the IDE.
    static const char* kPlain = "public static class Helpers { public static int Add(int a) => a; }\n";
    check(!fmt::parseActorClass(kPlain).anything(), "a plain helper class declares nothing");
}


// Editing what a class declares about ITSELF, and putting it back in the bytes it came from.
//
// This is a rewriter over ordinary hand-written code rather than a generated region, so it has no
// markers to hide behind: the only thing keeping a save out of the wrong line is that each value
// carries the span it was read from. Every case below is a way that goes wrong silently.
static void testClassDefaultsRewrite() {
    AVER_INFO("=== editing class defaults ===");

    static const char* kSrc =
        "using Aver.Framework;\n"
        "namespace Game;\n"
        "\n"
        "[AverClass(\"Hero\")]\n"
        "public sealed class Hero : AverCharacter\n"
        "{\n"
        "    public static void Configure(ClassBuilder b) => b.Camera(70f, 5f, 100000f);\n"
        "    public override void OnBeginPlay(BeginReason r)\n"
        "    {\n"
        "        Height    = 180f;   // a person, in centimetres\n"
        "        Radius    = 34f;\n"
        "        EyeHeight = 165f;\n"
        "    }\n"
        "}\n"
        "\n"
        "[AverClass(\"Prop\")]\n"
        "public sealed class Prop : AverActor\n"
        "{\n"
        "    public static void Configure(ClassBuilder b) => b.Mesh(\"Meshes/crate.ocmesh\", \"M_Wood\");\n"
        "    public int Height = 999;\n"
        "}\n";

    std::vector<fmt::ActorClassInfo> all = fmt::parseActorClasses(kSrc);
    check(all.size() == 2, "two classes");
    if (all.size() != 2) return;

    check(all[0].kind == fmt::ActorKind::Character, "the first is a Character");
    check(near(all[0].capsuleHeight, 180.0f) && near(all[0].capsuleRadius, 34.0f), "with its capsule read");
    check(all[0].capsuleHeightSpan.valid(), "and a span for the height");
    check(all[1].hasMesh && all[1].material == "M_Wood", "the second declares a mesh and material");

    // The span must point at the value and nothing else. Checked against the source directly,
    // because a span that is off by the width of a quote writes into the syntax around the value.
    const std::string src(kSrc);
    check(src.substr(all[0].capsuleHeightSpan.begin,
                     all[0].capsuleHeightSpan.end - all[0].capsuleHeightSpan.begin) == "180f",
          "the height span covers exactly the literal");
    check(src.substr(all[1].meshPathSpan.begin,
                     all[1].meshPathSpan.end - all[1].meshPathSpan.begin) == "Meshes/crate.ocmesh",
          "the mesh span covers the path WITHOUT its quotes");

    AVER_INFO("=== writing them back ===");
    {
        fmt::ActorClassInfo hero = all[0];
        hero.capsuleHeight = 195.0f;
        hero.eyeHeight = 178.0f;
        hero.cameraFovDeg = 90.0f;

        std::string out, err;
        check(fmt::rewriteActorClass(kSrc, hero, out, &err), "it rewrites: " + err);
        check(out.find("Height    = 195f;") != std::string::npos, "the height is written");
        check(out.find("EyeHeight = 178f;") != std::string::npos, "and the eye height");
        check(out.find("b.Camera(90f, 5f, 100000f)") != std::string::npos,
              "and one camera argument, leaving the other two alone");
        check(out.find("Radius    = 34f;") != std::string::npos, "an untouched field is untouched");
        // The COMMENT beside the value survives. This rewriter edits ordinary code, and a save that
        // ate somebody's trailing comment would be a save nobody uses twice.
        check(out.find("// a person, in centimetres") != std::string::npos, "the trailing comment survives");

        // THE OTHER CLASS IS UNTOUCHED, and `public int Height = 999;` is the trap: a rewriter that
        // searched for the field name instead of using the span would rewrite the wrong class's
        // Height, and both files would still compile.
        check(out.find("public int Height = 999;") != std::string::npos,
              "a same-named field in ANOTHER class is not touched");
        check(out.find("[AverClass(\"Prop\")]") != std::string::npos, "and that class still stands");
    }

    AVER_INFO("=== strings, idempotence and refusals ===");
    {
        fmt::ActorClassInfo prop = all[1];
        prop.meshPath = "Meshes/barrel.ocmesh";
        prop.material = "M_Metal";
        std::string out, err;
        check(fmt::rewriteActorClass(kSrc, prop, out, &err), "a string value rewrites");
        check(out.find("b.Mesh(\"Meshes/barrel.ocmesh\", \"M_Metal\")") != std::string::npos,
              "both literals are replaced, quotes intact");
        check(out.find("Height    = 180f;") != std::string::npos, "the character is untouched by it");

        // Saving what was read changes nothing. A save that reformatted every number would put a
        // diff in every commit whether or not anything moved.
        std::string same;
        check(fmt::rewriteActorClass(kSrc, all[0], same, &err) && same == src,
              "rewriting with the values as read is byte-identical");

        // A class with no spans at all writes nothing rather than failing.
        fmt::ActorClassInfo empty;
        std::string untouched;
        check(fmt::rewriteActorClass(kSrc, empty, untouched, &err) && untouched == src,
              "a class carrying no spans leaves the file alone");
    }

    AVER_INFO("=== values that cannot be written back ===");
    {
        // A non-literal is READ as "the feature is declared" but carries NO span, so the editor shows
        // no control for it. Offering a box that silently would not save is worse than offering none.
        static const char* kConst =
            "[AverClass(\"C\")]\n"
            "public sealed class C : AverActor {\n"
            "    public static void Configure(ClassBuilder b) => b.Camera(DefaultFov, 1f, 2f);\n"
            "}\n";
        const fmt::ActorClassInfo c = fmt::parseActorClass(kConst);
        check(c.hasCamera, "the camera is still recognised as declared");
        check(!c.cameraSpan[0].valid(), "but its first argument has no span, so nothing offers to edit it");
        check(c.cameraSpan[1].valid(), "while the literals after it do");
    }
}

int main() {
    testClassLevelActor();
    testClassDefaultsRewrite();

    AVER_INFO("=== reading the generated region ===");
    {
        const fmt::ActorScript s = fmt::parseActorScript(kCar);
        check(s.status == fmt::ActorParseStatus::Ok, "it parses: " + s.error);
        check(s.backend == fmt::ActorParserBackend::Builtin, "through the built-in scanner");
        check(s.models.size() == 2, "two placements");
        if (s.models.size() == 2) {
            check(s.models[0].objectId == 0x9E1C6A4B7F0D2233ULL, "the full 64-bit ObjectId survives");
            check(s.models[0].property == "Body", "and the property name");
            check(s.models[0].material == "M_CarPaint", "and the material");
            check(near(s.models[0].pos[2], 45.0f), "and the coordinates");
            check(near(s.models[1].pos[0], 120.0f) && near(s.models[1].pos[1], 80.0f),
                  "of the second row too");
            check(near(s.models[1].scale[0], 1.0f), "scale defaults through as authored");
        }
    }

    AVER_INFO("=== the mesh path both halves must agree on ===");
    {
        // THE LIVE BUG this normalisation exists for: the engine registers meshes under
        // fnv1a64("Meshes/cube.ocmesh") while the sample writes "Content/Meshes/CarBody.ocmesh".
        // Different hash, so the placement resolves to an id nothing holds and the child draws
        // nothing, silently.
        check(fmt::canonicalMeshPath("Content/Meshes/CarBody.ocmesh") == "Meshes/CarBody.ocmesh",
              "a Content/ prefix is stripped");
        check(fmt::canonicalMeshPath("Meshes/Wheel.ocmesh") == "Meshes/Wheel.ocmesh",
              "an already-canonical path is unchanged");
        check(fmt::canonicalMeshPath("Content\\Meshes\\A.ocmesh") == "Meshes/A.ocmesh",
              "backslashes become forward slashes");
        check(fmt::canonicalMeshPath("./Content/Meshes/A.ocmesh") == "Meshes/A.ocmesh",
              "a leading ./ goes too");
        // NOT stripped: a folder that merely begins with those letters. Getting this wrong would
        // silently repoint every asset under it.
        check(fmt::canonicalMeshPath("ContentPacks/Meshes/A.ocmesh") == "ContentPacks/Meshes/A.ocmesh",
              "a folder merely starting with 'Content' is left alone");
    }

    AVER_INFO("=== rewriting one row ===");
    {
        fmt::ActorScript s = fmt::parseActorScript(kCar);
        std::vector<fmt::ActorModel> edits;
        fmt::ActorModel e = s.models[0];
        e.pos[0] = 12.5f; e.pos[1] = -3.0f; e.pos[2] = 45.0f;
        e.rot[1] = 90.0f;
        edits.push_back(e);

        std::string out, err;
        check(fmt::rewriteActorScript(kCar, edits, out, &err), "it rewrites: " + err);
        check(out.find("pos: (12.5f, -3f, 45f)") != std::string::npos, "the dragged position is written");
        check(out.find("rot: (0f, 90f, 0f)") != std::string::npos, "and the rotation");

        // THE NEIGHBOUR IS UNTOUCHED. A rewriter matching by line number or by order rather than by
        // ObjectId would move the wrong model, and both files would still compile.
        check(out.find("WheelFL = b.Place(0x3A77B0110C55E9F2UL, \"Meshes/Wheel.ocmesh\", "
                       "material: \"M_Rubber\", pos: (120f, 80f, 20f)") != std::string::npos,
              "the other placement is byte-identical");

        // And everything outside the region.
        check(out.find("// <auto-generated/>") != std::string::npos, "the header survives");
        check(out.find("namespace Sample.Game;") != std::string::npos, "the namespace survives");
        check(out.find("partial class Car") != std::string::npos, "the class header survives");
        check(out.find("[Model] public ModelHandle Body") != std::string::npos,
              "the property declarations survive");

        // Only the tuples change. The mesh and material are read-only to a coordinate save: changing
        // a mesh from a gizmo drag would be surprising, so the format forbids it here.
        check(out.find("\"Content/Meshes/CarBody.ocmesh\", material: \"M_CarPaint\"") != std::string::npos,
              "the mesh and material are not rewritten by a coordinate save");
    }

    AVER_INFO("=== idempotence and no-ops ===");
    {
        fmt::ActorScript s = fmt::parseActorScript(kCar);
        std::string once, twice, err;
        check(fmt::rewriteActorScript(kCar, s.models, once, &err), "rewriting with what was read");
        // Byte-identical to the input. A save that reformats every number would put a diff in every
        // commit whether or not anything moved.
        check(once == std::string(kCar), "an unedited save changes NOTHING");
        check(fmt::rewriteActorScript(once, s.models, twice, &err) && twice == once,
              "and doing it twice changes nothing again");

        // An id the file does not contain is ignored, not appended. Adding a placement has to mint an
        // id and declare a property, so it is a different operation with different rules.
        fmt::ActorModel ghost;
        ghost.objectId = 0xDEADBEEFULL;
        std::string out;
        check(fmt::rewriteActorScript(kCar, {ghost}, out, &err) && out == std::string(kCar),
              "an unknown ObjectId is ignored rather than appended");
    }

    AVER_INFO("=== what the scanner declines ===");
    {
        std::string out, err;

        // No region at all is NOT an error: a hand-written actor with no designer file is ordinary.
        const fmt::ActorScript none = fmt::parseActorScript("class Plain {}\n");
        check(none.status == fmt::ActorParseStatus::NoRegion, "a file with no region reports NoRegion");
        check(!fmt::rewriteActorScript("class Plain {}\n", {}, out, &err), "and cannot be rewritten");

        // A newer schema is left alone and surfaced, never guessed at.
        const char* newer =
            "// <aver-generated region=\"models\" schema=\"2\">\n"
            "// </aver-generated>\n";
        const fmt::ActorScript s2 = fmt::parseActorScript(newer);
        check(s2.status == fmt::ActorParseStatus::UnknownSchema, "an unknown schema is refused");
        check(s2.error.find("schema") != std::string::npos, "and says so");

        // An open marker with no close.
        const fmt::ActorScript unterminated =
            fmt::parseActorScript("// <aver-generated region=\"models\" schema=\"1\">\nx\n");
        check(unterminated.status == fmt::ActorParseStatus::Malformed, "an unclosed region is Malformed");

        // MALFORMED IS THE ESCALATION SIGNAL, not a verdict on the file. Each of these is legal C#
        // that the locked grammar forbids, and each is exactly what the Roslyn backend is for.
        const char* reordered =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x1UL, \"m.ocmesh\", pos: (0f, 0f, 0f), material: \"M\", rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        const fmt::ActorScript ro = fmt::parseActorScript(reordered);
        check(ro.status == fmt::ActorParseStatus::Malformed,
              "reordered named arguments are declined, not misread");

        const char* expression =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x1UL, \"m.ocmesh\", material: \"M\", pos: (Offset + 1f, 0f, 0f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        check(fmt::parseActorScript(expression).status == fmt::ActorParseStatus::Malformed,
              "a coordinate written as an expression is declined");

        // An int where a float literal belongs does not compile in C#, so reading it as 1.0f would be
        // inventing a value the compiler never accepted.
        const char* noSuffix =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x1UL, \"m.ocmesh\", material: \"M\", pos: (0, 0, 0), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        check(fmt::parseActorScript(noSuffix).status == fmt::ActorParseStatus::Malformed,
              "a coordinate missing its f suffix is declined");

        // Two rows sharing the match key makes every rewrite ambiguous, and the symptom would be a
        // drag that moves the wrong model.
        const char* dupes =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x7UL, \"m.ocmesh\", material: \"M\", pos: (0f, 0f, 0f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "        B = b.Place(0x7UL, \"m.ocmesh\", material: \"M\", pos: (1f, 0f, 0f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        const fmt::ActorScript dup = fmt::parseActorScript(dupes);
        check(dup.status == fmt::ActorParseStatus::Malformed, "duplicate ObjectIds are refused");
        check(dup.error.find("key") != std::string::npos, "and the reason names the key");
    }

    AVER_INFO("=== a marker that is not a marker ===");
    {
        // The needle inside a string must not open a region. Matched anchored to `//` at the start of
        // a line for exactly this reason.
        const char* decoy =
            "class X { string s = \"// <aver-generated region=\\\"models\\\" schema=\\\"1\\\">\"; }\n";
        check(fmt::parseActorScript(decoy).status == fmt::ActorParseStatus::NoRegion,
              "the marker text inside a string literal does not open a region");
    }

    if (g_failures == 0) AVER_INFO("=== all actor script tests passed ===");
    else                 AVER_ERROR("=== {} FAILED ===", g_failures);
    return g_failures == 0 ? 0 : 1;
}
