// Reading and rewriting a `.Designer.cs` — the actor editor's half of the file.
//
// Every property below is one a viewport and a gizmo depend on and neither can show you: a drag
// writes a number into somebody's source, and the ways that goes wrong are all silent. The wrong row
// moves. A neighbouring model loses a digit. The hand-written half is touched. A file the scanner
// should have declined is half-rewritten instead.
#include "aver/formats/ActorScript.hpp"
#include "aver/core/Log.hpp"

#include <cmath>
#include <string>

using namespace aver;

static int g_failures = 0;

static void check(bool cond, const std::string& what) {
    if (cond) { AVER_INFO("  ok    {}", what); return; }
    ++g_failures;
    AVER_ERROR("  FAIL  {}", what);
}

static bool near(f32 a, f32 b, f32 eps = 1e-4f) { return std::fabs(a - b) <= eps; }

// The real sample from the tree, trimmed to what matters.
static const char* kCar =
    "// <auto-generated/>\n"
    "using Aver.Framework;\n"
    "\n"
    "namespace Sample.Game;\n"
    "\n"
    "partial class Car\n"
    "{\n"
    "    // <aver-generated region=\"models\" schema=\"1\"> DO NOT EDIT\n"
    "    [Model] public ModelHandle Body    { get; private set; }\n"
    "    [Model] public ModelHandle WheelFL { get; private set; }\n"
    "\n"
    "    protected override void BuildModels(ActorBuilder b)\n"
    "    {\n"
    "        Body    = b.Place(0x9E1C6A4B7F0D2233UL, \"Content/Meshes/CarBody.ocmesh\", material: \"M_CarPaint\", pos: (0f, 0f, 45f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
    "        WheelFL = b.Place(0x3A77B0110C55E9F2UL, \"Meshes/Wheel.ocmesh\", material: \"M_Rubber\", pos: (120f, 80f, 20f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
    "    }\n"
    "    // </aver-generated>\n"
    "}\n";

int main() {
    AVER_INFO("=== reading the generated region ===");
    {
        const fmt::ActorScript s = fmt::parseActorScript(kCar);
        check(s.status == fmt::ActorParseStatus::Ok, "it parses: " + s.error);
        check(s.backend == fmt::ActorParserBackend::Builtin, "through the built-in scanner");
        check(s.models.size() == 2, "two placements");
        if (s.models.size() == 2) {
            check(s.models[0].objectId == 0x9E1C6A4B7F0D2233ULL, "the full 64-bit ObjectId survives");
            check(s.models[0].property == "Body", "and the property name");
            check(s.models[0].material == "M_CarPaint", "and the material");
            check(near(s.models[0].pos[2], 45.0f), "and the coordinates");
            check(near(s.models[1].pos[0], 120.0f) && near(s.models[1].pos[1], 80.0f),
                  "of the second row too");
            check(near(s.models[1].scale[0], 1.0f), "scale defaults through as authored");
        }
    }

    AVER_INFO("=== the mesh path both halves must agree on ===");
    {
        // THE LIVE BUG this normalisation exists for: the engine registers meshes under
        // fnv1a64("Meshes/cube.ocmesh") while the sample writes "Content/Meshes/CarBody.ocmesh".
        // Different hash, so the placement resolves to an id nothing holds and the child draws
        // nothing, silently.
        check(fmt::canonicalMeshPath("Content/Meshes/CarBody.ocmesh") == "Meshes/CarBody.ocmesh",
              "a Content/ prefix is stripped");
        check(fmt::canonicalMeshPath("Meshes/Wheel.ocmesh") == "Meshes/Wheel.ocmesh",
              "an already-canonical path is unchanged");
        check(fmt::canonicalMeshPath("Content\\Meshes\\A.ocmesh") == "Meshes/A.ocmesh",
              "backslashes become forward slashes");
        check(fmt::canonicalMeshPath("./Content/Meshes/A.ocmesh") == "Meshes/A.ocmesh",
              "a leading ./ goes too");
        // NOT stripped: a folder that merely begins with those letters. Getting this wrong would
        // silently repoint every asset under it.
        check(fmt::canonicalMeshPath("ContentPacks/Meshes/A.ocmesh") == "ContentPacks/Meshes/A.ocmesh",
              "a folder merely starting with 'Content' is left alone");
    }

    AVER_INFO("=== rewriting one row ===");
    {
        fmt::ActorScript s = fmt::parseActorScript(kCar);
        std::vector<fmt::ActorModel> edits;
        fmt::ActorModel e = s.models[0];
        e.pos[0] = 12.5f; e.pos[1] = -3.0f; e.pos[2] = 45.0f;
        e.rot[1] = 90.0f;
        edits.push_back(e);

        std::string out, err;
        check(fmt::rewriteActorScript(kCar, edits, out, &err), "it rewrites: " + err);
        check(out.find("pos: (12.5f, -3f, 45f)") != std::string::npos, "the dragged position is written");
        check(out.find("rot: (0f, 90f, 0f)") != std::string::npos, "and the rotation");

        // THE NEIGHBOUR IS UNTOUCHED. A rewriter matching by line number or by order rather than by
        // ObjectId would move the wrong model, and both files would still compile.
        check(out.find("WheelFL = b.Place(0x3A77B0110C55E9F2UL, \"Meshes/Wheel.ocmesh\", "
                       "material: \"M_Rubber\", pos: (120f, 80f, 20f)") != std::string::npos,
              "the other placement is byte-identical");

        // And everything outside the region.
        check(out.find("// <auto-generated/>") != std::string::npos, "the header survives");
        check(out.find("namespace Sample.Game;") != std::string::npos, "the namespace survives");
        check(out.find("partial class Car") != std::string::npos, "the class header survives");
        check(out.find("[Model] public ModelHandle Body") != std::string::npos,
              "the property declarations survive");

        // Only the tuples change. The mesh and material are read-only to a coordinate save: changing
        // a mesh from a gizmo drag would be surprising, so the format forbids it here.
        check(out.find("\"Content/Meshes/CarBody.ocmesh\", material: \"M_CarPaint\"") != std::string::npos,
              "the mesh and material are not rewritten by a coordinate save");
    }

    AVER_INFO("=== idempotence and no-ops ===");
    {
        fmt::ActorScript s = fmt::parseActorScript(kCar);
        std::string once, twice, err;
        check(fmt::rewriteActorScript(kCar, s.models, once, &err), "rewriting with what was read");
        // Byte-identical to the input. A save that reformats every number would put a diff in every
        // commit whether or not anything moved.
        check(once == std::string(kCar), "an unedited save changes NOTHING");
        check(fmt::rewriteActorScript(once, s.models, twice, &err) && twice == once,
              "and doing it twice changes nothing again");

        // An id the file does not contain is ignored, not appended. Adding a placement has to mint an
        // id and declare a property, so it is a different operation with different rules.
        fmt::ActorModel ghost;
        ghost.objectId = 0xDEADBEEFULL;
        std::string out;
        check(fmt::rewriteActorScript(kCar, {ghost}, out, &err) && out == std::string(kCar),
              "an unknown ObjectId is ignored rather than appended");
    }

    AVER_INFO("=== what the scanner declines ===");
    {
        std::string out, err;

        // No region at all is NOT an error: a hand-written actor with no designer file is ordinary.
        const fmt::ActorScript none = fmt::parseActorScript("class Plain {}\n");
        check(none.status == fmt::ActorParseStatus::NoRegion, "a file with no region reports NoRegion");
        check(!fmt::rewriteActorScript("class Plain {}\n", {}, out, &err), "and cannot be rewritten");

        // A newer schema is left alone and surfaced, never guessed at.
        const char* newer =
            "// <aver-generated region=\"models\" schema=\"2\">\n"
            "// </aver-generated>\n";
        const fmt::ActorScript s2 = fmt::parseActorScript(newer);
        check(s2.status == fmt::ActorParseStatus::UnknownSchema, "an unknown schema is refused");
        check(s2.error.find("schema") != std::string::npos, "and says so");

        // An open marker with no close.
        const fmt::ActorScript unterminated =
            fmt::parseActorScript("// <aver-generated region=\"models\" schema=\"1\">\nx\n");
        check(unterminated.status == fmt::ActorParseStatus::Malformed, "an unclosed region is Malformed");

        // MALFORMED IS THE ESCALATION SIGNAL, not a verdict on the file. Each of these is legal C#
        // that the locked grammar forbids, and each is exactly what the Roslyn backend is for.
        const char* reordered =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x1UL, \"m.ocmesh\", pos: (0f, 0f, 0f), material: \"M\", rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        const fmt::ActorScript ro = fmt::parseActorScript(reordered);
        check(ro.status == fmt::ActorParseStatus::Malformed,
              "reordered named arguments are declined, not misread");

        const char* expression =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x1UL, \"m.ocmesh\", material: \"M\", pos: (Offset + 1f, 0f, 0f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        check(fmt::parseActorScript(expression).status == fmt::ActorParseStatus::Malformed,
              "a coordinate written as an expression is declined");

        // An int where a float literal belongs does not compile in C#, so reading it as 1.0f would be
        // inventing a value the compiler never accepted.
        const char* noSuffix =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x1UL, \"m.ocmesh\", material: \"M\", pos: (0, 0, 0), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        check(fmt::parseActorScript(noSuffix).status == fmt::ActorParseStatus::Malformed,
              "a coordinate missing its f suffix is declined");

        // Two rows sharing the match key makes every rewrite ambiguous, and the symptom would be a
        // drag that moves the wrong model.
        const char* dupes =
            "// <aver-generated region=\"models\" schema=\"1\">\n"
            "        A = b.Place(0x7UL, \"m.ocmesh\", material: \"M\", pos: (0f, 0f, 0f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "        B = b.Place(0x7UL, \"m.ocmesh\", material: \"M\", pos: (1f, 0f, 0f), rot: (0f, 0f, 0f), scale: (1f, 1f, 1f));\n"
            "// </aver-generated>\n";
        const fmt::ActorScript dup = fmt::parseActorScript(dupes);
        check(dup.status == fmt::ActorParseStatus::Malformed, "duplicate ObjectIds are refused");
        check(dup.error.find("key") != std::string::npos, "and the reason names the key");
    }

    AVER_INFO("=== a marker that is not a marker ===");
    {
        // The needle inside a string must not open a region. Matched anchored to `//` at the start of
        // a line for exactly this reason.
        const char* decoy =
            "class X { string s = \"// <aver-generated region=\\\"models\\\" schema=\\\"1\\\">\"; }\n";
        check(fmt::parseActorScript(decoy).status == fmt::ActorParseStatus::NoRegion,
              "the marker text inside a string literal does not open a region");
    }

    if (g_failures == 0) AVER_INFO("=== all actor script tests passed ===");
    else                 AVER_ERROR("=== {} FAILED ===", g_failures);
    return g_failures == 0 ? 0 : 1;
}
